### ISSUE TITLE
Issue with User UpdateMetadata Function

### ISSUE THREAD

**Issue by dgocoder** [clerkinc/clerk-sdk-go#109]
I've been trying to use this method to update the public metadata and it doesn't seem to work. I've used the backend api restfully with no problem.

```go
        client, err := clerk.NewClient(os.Getenv("CLERK_SECRET_KEY"))
	if err != nil {
		return nil, err
	}

	cx := map[string]interface{}{
		"workspaces": map[string]bool{
			"123": true,
		},
	}
	_, err = client.Users().UpdateMetadata("user_2XXXXXXXXXXXX", &clerk.UpdateUserMetadata{
		PublicMetadata: cx,
	})
```
When I make this call the user comes back with a public metadata of empty. Logging inside the package it appears to be sending it in the request however it does nothing.

Printing out the req and res in the package internally i see this.

req/res
`&{PATCH https://api.clerk.dev/v1/users/user_2XXXXXXXXXXXX/metadata HTTP/1.1 1 1 map[X-Clerk-Sdk:[go/1.36.1]] {{"public_metadata":{"workspaces":{"123":true}},"private_metadata":null,"unsafe_metadata":null}
|  +176ms  } 0x10441f590 112 [] false api.clerk.dev map[] map[] <nil> map[]   <nil> <nil> <nil> 0x14000038118}
|  +375ms  &{200 OK 200 HTTP/2.0 2 0 map[Cf-Cache-Status:[DYNAMIC] Cf-Ray:[7ab14e6cf8502e64-DFW] Content-Type:[application/json] Date:[Mon, 20 Mar 2023 22:14:08 GMT] Server:[cloudflare] X-Cloud-Trace-Context:[ec7d191b85f3c99ebb21ceaac484a24b]] 0x1400018c040 -1 [] false true map[] 0x140002a2200 0x14000128790}`

Not really sure what could be causing the problem here but it is responding with a 200 status. Happy to write my own rest request but I thought it was worth calling out or at least showing me what I could be doing wrong.

Appreciate the help in advance

**Comment by dgocoder** [comment]
This code worked without issue. Just figured i'd share

```go
func (a clerky) SetWorkspaceIDs(ctx context.Context, userID string, workspaceID string) error {
	url := fmt.Sprintf("https://api.clerk.dev/v1/users/%s/metadata", userID)
	method := "PATCH"

	payload := map[string]interface{}{
		"public_metadata": map[string]interface{}{
			"workspaces": map[string]bool{
				workspaceID: true,
			},
		},
	}

	json, err := json.Marshal(payload)
	if err != nil {
		return err
	}
	fmt.Println(string(json))
	client := &http.Client{}
	req, err := http.NewRequest(method, url, bytes.NewReader(json))
	if err != nil {
		fmt.Println(err)
		return err
	}
	req.Header.Add("Authorization", fmt.Sprintf("Bearer %s", os.Getenv("CLERK_SECRET_KEY")))
	req.Header.Add("Content-Type", "application/json")

	res, err := client.Do(req)
	if err != nil {
		fmt.Println(err)
		return err
	}
	defer res.Body.Close()

	return nil
}
```

**Comment by gkats** [comment]
@dgocoder Thanks for reporting.

The metadata properties on the users service should be `[]byte` (or `json.RawMessage` to be exact). Meaning that you should send the JSON encoded bytes to the response and not a map.

I can see why this is confusing though. The metadata fields have the wrong type. They are typed as `interface{}` which implies that a map can be used. This is wrong and we should update it.

In the meantime, can you try the same operation but encode the metadata first?
```go
client, err := clerk.NewClient(os.Getenv("CLERK_SECRET_KEY"))
if err != nil {
  return nil, err
}

cx := map[string]interface{}{
  "workspaces": map[string]bool{
    "123": true,
  },
}

enc, err := json.Marshal(cx)
if err != nil {
  return nil, err
}

_, err = client.Users().UpdateMetadata("user_2XXXXXXXXXXXX", &clerk.UpdateUserMetadata{
  PublicMetadata: enc,
})
```

It would be awesome if you'd be willing to contribute a PR to fix this. We basically have to change all the [user metadata types](https://github.com/clerkinc/clerk-sdk-go/blob/efd909d8d336ce7af469660779bf5f38dc706581/clerk/users.go#L33) (`PublicMetadata`, `PrivateMetadata` and `UnsafeMetadata`) to `json.RawMessage`, similar to [how it is for organizations](https://github.com/clerkinc/clerk-sdk-go/blob/efd909d8d336ce7af469660779bf5f38dc706581/clerk/organizations.go#L20) for example.

**Comment by gkats** [comment]
> would it not be best to have the type be map[string]interface{} and have library marshal it?

@dgocoder I think `json.RawMessage` offers more flexibility. If we type the metadata as `map[string]interface{}` then we limit the options of the consumer. 

What if consumers have custom types (structs) for their metadata? 

I think it's best if we accept the JSON encoded value and leave it up to the consumer to take care of serialization/deserialization.

**Comment by dgocoder** [comment]
@gkats pr is up ^

**Comment by dgocoder** [comment]
Closing issue as pr was merged
