### ISSUE TITLE
v2 really ready for release?

### ISSUE THREAD

**Issue by Hades32** [clerkinc/clerk-sdk-go#112]
I just got a PR from [Renovate Bot](https://docs.renovatebot.com/) to upgrade to v2.0.0 of this package. But honestly that single commit in this branch doesn't look like a ready release.

If this is basically your working branch then I suggest renaming it to `v2-dev` (or something along those lines), then it would be correctly identified as a pre-release according to semver. When you're done you can rename it again to `v2` and create proper tags on top

cc @chanioxaris

**Comment by chanioxaris** [comment]
Hello @Hades32 and sorry for the trouble here. Indeed there was a `v2` branch as we were looking for a new v2 for our SDK but it was part of testing the release process. I went ahead and deleted the branch, to prevent such issues. Definitely not ready and we will inform everyone for the changes when the time comes 😄
