### ISSUE TITLE
Error with basic JWT example: no jwk key found for kid ins_<redacted>

### ISSUE THREAD

**Issue by EwanValentine** [clerkinc/clerk-sdk-go#132]
Hi there,

I'm trying to use Clerk + Golang to protect a backend API, however, when I grab a JWT from our front-end and try to run it against the basic example from the docs, I get the error:

```
no jwk key found for kid ins_<redacted>
```

So there is a `kid` set in the JWT, but I'm not sure what the value of that relates to or why it's not valid

Here's the code I'm running:
```golang
package main

import (
	"log"
	"net/http"
	"strings"

	"github.com/clerkinc/clerk-sdk-go/clerk"
)

func main() {
	client, _ := clerk.NewClient("<redacted>")

	http.HandleFunc("/hello", func(w http.ResponseWriter, r *http.Request) {
		// get session token from Authorization header
		sessionToken := r.Header.Get("Authorization")
		sessionToken = strings.TrimPrefix(sessionToken, "Bearer ")

		// verify the session
		sessClaims, err := client.VerifyToken(sessionToken)
		if err != nil {
			log.Println(err)
			w.WriteHeader(http.StatusUnauthorized)
			w.Write([]byte("Unauthorized"))
			return
		}

		// get the user, and say welcome!
		user, err := client.Users().Read(sessClaims.Claims.Subject)
		if err != nil {
			panic(err)
		}

		w.Write([]byte("Welcome " + *user.FirstName))
	})

	http.ListenAndServe(":8080", nil)
}

```

**Comment by georgepsarakis** [comment]
Hello @EwanValentine ! Sorry that you encountered an issue here. This error can occur if you're trying to verify a session token that belongs to a different Clerk instance than the one your SDK Client has been configured with. 

Essentially, you need to ensure first when initializing the client (`clerk.NewClient("<redacted>")` in your snippet) that the API secret key and the token under verification both belong to the same instance.

I hope this helps, please let us know if you need further assistance!

**Comment by EwanValentine** [comment]
@georgepsarakis I do have another potentially silly issue actually, I'll raise a separate issue though :)
