### ISSUE TITLE
Session expired in two minutes

### ISSUE THREAD

**Issue by EwanValentine** [clerkinc/clerk-sdk-go#133]
I can see from [here](https://twitter.com/tweetsbycolin/status/1644137146503286786) and [here](https://clerk.com/docs/build-frontend-first/session-authentication) that tokens expire every two minutes, and that there's a refresh mechanism in place. Which means I'm getting 'token expired' errors when trying to validate an API endpoint call.

The front-end's written in NextJS and follows the standard NextJS setup (I don't have access to this codebase so can't provide an example, I can probably get a copy of the relevant file from the UI if needed though...)   

Is there anything I need to do from a back-end perspective to enable this refresh mechanism? Thanks!

Example code: 
```golang
package main

import (
	"log"
	"net/http"
	"strings"

	"github.com/clerkinc/clerk-sdk-go/clerk"
)

func main() {
	client, _ := clerk.NewClient("<redacted>")

	http.HandleFunc("/hello", func(w http.ResponseWriter, r *http.Request) {
		// get session token from Authorization header
		sessionToken := r.Header.Get("Authorization")
		sessionToken = strings.TrimPrefix(sessionToken, "Bearer ")

		// verify the session
		sessClaims, err := client.VerifyToken(sessionToken)
		if err != nil {
			log.Println(err)
			w.WriteHeader(http.StatusUnauthorized)
			w.Write([]byte("Unauthorized"))
			return
		}

		// get the user, and say welcome!
		user, err := client.Users().Read(sessClaims.Claims.Subject)
		if err != nil {
			panic(err)
		}

		w.Write([]byte("Welcome " + *user.FirstName))
	})

	http.ListenAndServe(":8080", nil)
}
```

**Comment by georgepsarakis** [comment]
@EwanValentine are you still facing the same issue? Let us know if there are any updates or you need further help!

**Comment by EwanValentine** [comment]
My apologies @chanioxaris // @georgepsarakis you're absolutely correct, was quick fix from the front-end to send the session token rather than the initial token. Much appreciated and sorry for the slow response!

**Comment by georgepsarakis** [comment]
No worries, glad that we could help!
