### ISSUE TITLE
Bad link to Auth V2 (404)

### ISSUE THREAD

**Issue by wyattlefevre** [clerkinc/clerk-sdk-go#154]
The bottom of the readme mentions [auth v2](https://github.com/clerkinc/clerk-sdk-go#:~:text=If%20you%27re%20using%20the%20newly%2Dintroduced%20Auth%20v2%20scheme%2C%20you%27ll%20have%20to%20use%20the%20clerk.WithSessionV2()%20middleware%2C%20instead%20of%20clerk.WithSession().), however, the link is a dead end and I can't find anything about auth v2 in a quick google search. I suspect the readme is out of date?

**Comment by gkats** [comment]
Hello @wyattlefevre, thanks for opening this issue.

The README is slightly out of date, but the recommended way to handle requests is indeed the `clerk.WithSessionV2` middleware.

What the README mentions as Auth v2 is currently the de-facto authentication and session management scheme that Clerk uses.

We'll try to update the README and our docs soon.

In the meantime, please let us know if you need any help with the integration.
