### ISSUE TITLE
V2 middleware does not permit requests without authentication

### ISSUE THREAD

**Issue by notproperlycut** [clerkinc/clerk-sdk-go#35]
Hi, I've spoken with @SokratisVidros about this, who requested I add this issue.

We're trying to use your V2 auth middleware. One reason is so that we can use `WithSessionV2` to populate session claims into request context if we have a signed-in user, but permit the request even if we do not. The [README](https://github.com/clerkinc/clerk-sdk-go/blob/main/README.md) suggests that `RequireSessionV2` is for cases where one wants to be more strict about unauthorized requests.

In our instance, we are serving a graphQL endpoint behind `WithSessionV2`. For some requests, we do not want or need a signed-in user. For instance: we use [this npm package](https://github.com/prisma-labs/get-graphql-schema) to pull the schema from our endpoint, as part of our dev/build process.

Right now, completely header/cookie-free requests do not make it through the `WithSessionV2` handler. Instead we return some HTML designed to work with clerk-js and cause a retry. I might be wrong, but I believe it's [this line](https://github.com/clerkinc/clerk-sdk-go/blob/bf85e83891b0f02b673c7b619c20d62ef8bc5935/clerk/middleware_v2.go#L90) we are triggering.

This workflow worked for us previously, when we were using `client.Verification().Verify(r)` as described under "Auth v1 (deprecated)" [here](https://docs.clerk.dev/reference/backend-api-reference/sdks/golang/verifying-a-session). But since we moved to use the middleware, I don't see a way to let all requests through so that we can decide downstream, whether to 401/403

**Comment by chanioxaris** [comment]
Hey there @notproperlycut, thanks for reporting this. 

From what you described i believe the SDK wrongfully renders an interstitial page (to load clerk.js as you stated) which is irrelevant to your case. 

Can you please share how you are testing this, where the backend and frontend runs (e.g. http://localhost:4000), so i can reproduce it on my own and push a fix?

**Comment by notproperlycut** [comment]
Thanks @chanioxaris. The easiest way I found to trigger this condition, was to simply curl our endpoint running locally. So, with no frontend at all.

In my case...
```
$ curl http://localhost:8080/query              
<!DOCTYPE html>                                                                                                                                                                   
<html>                                                                                   
    <head>                                                                                                                                                                        
        <meta charset="UTF-8" />                                                         
    </head>                                                                              
    <body>                                                                               
        <script>                                                                                                                                                                  
            window.startClerk = async () => {                                            
                const Clerk = window.Clerk;
...
```

The prisma-labs/get-graphql-schema package I mentioned, is not doing much more than this, it will just make a headless request I'm sure.

Our auth middleware is structured like this, which will hopefully look sane to you:
```
func (auth *myClient) Handler(next http.Handler) http.Handler {
  handler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
    sessClaims, ok := clerk.SessionFromContext(r.Context())
    if ok {
      // Set our own data into context
    }

    next.ServeHTTP(w, r)
    },
  )

  injectActiveSession := clerk.WithSessionV2(auth.client)
  return injectActiveSession(handler)
}
```

**Comment by chanioxaris** [comment]
Thanks @notproperlycut for the info, we also got some more details regarding your use case from the team. We are looking for the best way to fix this

**Comment by chanioxaris** [comment]
Required changes have been merged
